name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
      - name: Build Docker image
        run: docker build -t event-management-backend .
      # - name: Push Docker image (add your registry info)
      #   run: docker push <your-registry>/event-management-backend 